/**
 * OrdersService — real-DB integration test (Part B).
 *
 * Purpose: prove that the ACTUAL SQL generated by TypeORM genuinely scopes
 * by organizationId (and optionally userId), so that cross-org and cross-user
 * IDOR is impossible at the database layer — not just at the in-memory fake
 * repo layer used by the unit tests.
 *
 * Infrastructure:
 *   - @testcontainers/postgresql spins a disposable Postgres container.
 *   - Real DataSource with synchronize:true (throwaway schema).
 *   - Real OrdersService wired to that DataSource — NO mocks, NO fakes.
 *
 * Seed layout:
 *   ORG_A / USER_1 → order_A1
 *   ORG_A / USER_2 → order_A2
 *   ORG_B / USER_1 → order_B1
 *
 * This test suite is intentionally excluded from the fast unit suite
 * (testRegex: *.int-spec.ts, run via `npm run test:integration`).
 * Docker must be available in the local environment.
 */

import { PostgreSqlContainer, StartedPostgreSqlContainer } from '@testcontainers/postgresql';
import { DataSource } from 'typeorm';
import { RpcException } from '@nestjs/microservices';

import { OrdersService } from './orders.service';
import { Order } from './entities/order.entity';
import { OrderItem } from './entities/order-item.entity';
import { OrderItemExtra } from './entities/order-item-extra.entity';
import { OrderItemRemovedIngredient } from './entities/order-item-removed-ingredient.entity';
import { OrderStatus } from 'src/common/enums/order-status.enum';
import { PaymentStatus } from 'src/common/enums/payment-status.enum';
import { OrderCurrency } from 'src/common/enums/order-currency.enum';

const ORG_A  = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
const ORG_B  = 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
const USER_1 = '11111111-1111-4111-8111-111111111111';
const USER_2 = '22222222-2222-4222-8222-222222222222';

describe('OrdersService — SQL scope (real Postgres via testcontainers)', () => {
  let pgContainer: StartedPostgreSqlContainer;
  let dataSource: DataSource;
  let service: OrdersService;

  let orderId_A1: string; // ORG_A, USER_1
  let orderId_A2: string; // ORG_A, USER_2
  let orderId_B1: string; // ORG_B, USER_1

  // Container startup can take 20–40 s on a cold Docker pull.
  beforeAll(async () => {
    pgContainer = await new PostgreSqlContainer('postgres:16-alpine').start();

    dataSource = new DataSource({
      type: 'postgres',
      host: pgContainer.getHost(),
      port: pgContainer.getPort(),
      database: pgContainer.getDatabase(),
      username: pgContainer.getUsername(),
      password: pgContainer.getPassword(),
      entities: [Order, OrderItem, OrderItemExtra, OrderItemRemovedIngredient],
      synchronize: true,
    });

    await dataSource.initialize();

    const fakeClientProxy = { emit: () => ({}), send: () => ({ toPromise: () => Promise.resolve(null) }) } as any;
    service = new OrdersService(dataSource, dataSource.getRepository(Order), fakeClientProxy, fakeClientProxy);

    // ── seed ──────────────────────────────────────────────────────────────
    const repo = dataSource.getRepository(Order);

    const baseOrder = {
      status: OrderStatus.PENDING,
      paymentStatus: PaymentStatus.PENDING,
      currency: OrderCurrency.EUR,
    };

    const a1 = repo.create({ ...baseOrder, organizationId: ORG_A, userId: USER_1, subtotal: 10, total: 10, orderNumber: 1, customerName: 'Alice' });
    orderId_A1 = (await repo.save(a1)).id;

    const a2 = repo.create({ ...baseOrder, organizationId: ORG_A, userId: USER_2, subtotal: 20, total: 20, orderNumber: 2, customerName: 'Bob' });
    orderId_A2 = (await repo.save(a2)).id;

    const b1 = repo.create({ ...baseOrder, organizationId: ORG_B, userId: USER_1, subtotal: 30, total: 30, orderNumber: 1, customerName: 'Carol' });
    orderId_B1 = (await repo.save(b1)).id;
  }, 60_000);

  afterAll(async () => {
    await dataSource?.destroy();
    await pgContainer?.stop();
  });

  // ─────────────────────────────────────────────────────────────────────────
  // Positive cases — real SQL returns the row
  // ─────────────────────────────────────────────────────────────────────────
  describe('positive — row found when scoping is correct', () => {
    it('STAFF: returns order when org matches (no userId filter)', async () => {
      const result = await service.findOne({ id: orderId_A1, organizationId: ORG_A });
      expect(result.id).toBe(orderId_A1);
    });

    it('CUSTOMER: returns order when org AND userId both match', async () => {
      const result = await service.findOne({ id: orderId_A1, organizationId: ORG_A, userId: USER_1 });
      expect(result.id).toBe(orderId_A1);
    });

    it('STAFF can see any order in the org regardless of userId', async () => {
      const r1 = await service.findOne({ id: orderId_A1, organizationId: ORG_A });
      const r2 = await service.findOne({ id: orderId_A2, organizationId: ORG_A });
      expect(r1.id).toBe(orderId_A1);
      expect(r2.id).toBe(orderId_A2);
    });
  });

  // ─────────────────────────────────────────────────────────────────────────
  // Negative cases — real SQL must NOT return the row (IDOR prevention)
  // ─────────────────────────────────────────────────────────────────────────
  describe('negative — cross-org IDOR (C-3 fix)', () => {
    it('throws when order belongs to ORG_B but request uses ORG_A scope', async () => {
      // Real WHERE: id = orderId_B1 AND organizationId = ORG_A → no row
      await expect(
        service.findOne({ id: orderId_B1, organizationId: ORG_A }),
      ).rejects.toThrow(RpcException);
    });

    it('throws even when the requester is the correct userId but wrong org', async () => {
      // USER_1 owns orderId_B1 in ORG_B, but scope says ORG_A → SQL returns nothing
      await expect(
        service.findOne({ id: orderId_B1, organizationId: ORG_A, userId: USER_1 }),
      ).rejects.toThrow(RpcException);
    });

    it('throws when orderId is valid but orgId is completely unrelated', async () => {
      const UNRELATED_ORG = 'cccccccc-cccc-cccc-cccc-cccccccccccc';
      await expect(
        service.findOne({ id: orderId_A1, organizationId: UNRELATED_ORG }),
      ).rejects.toThrow(RpcException);
    });
  });

  describe('negative — cross-user IDOR within same org', () => {
    it('throws when userId does not own the order (same org)', async () => {
      // order_A1 belongs to USER_1; USER_2 should not see it
      await expect(
        service.findOne({ id: orderId_A1, organizationId: ORG_A, userId: USER_2 }),
      ).rejects.toThrow(RpcException);
    });

    it('throws when userId does not own the order even if id is a valid order in org', async () => {
      // order_A2 belongs to USER_2; USER_1 should not see it
      await expect(
        service.findOne({ id: orderId_A2, organizationId: ORG_A, userId: USER_1 }),
      ).rejects.toThrow(RpcException);
    });
  });

  describe('negative — nonexistent ids', () => {
    it('throws for a random UUID that does not exist', async () => {
      await expect(
        service.findOne({ id: 'ffffffff-ffff-ffff-ffff-ffffffffffff', organizationId: ORG_A }),
      ).rejects.toThrow(RpcException);
    });
  });
});
